markdown: redcarpet
permalink: /:title.html
url: http://fangjh.github.io
lsi: true
pygments: true
safe: true
auto: true
timezone: Asia/Shanghai


# presonal config
title: 涂鸦
feed: http://fangjh.github.io/feed.xml
comments: disqus

author:
  name: Chris Fang
  nickname: Chris
  email: fangjh@gmail.com
  gmail: fangjh@gmail.com

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:

zh-CN:
  date:
    abbr_day_names:
    - 日
    - 一
    - 二
    - 三
    - 四
    - 五
    - 六
    abbr_month_names:
    -
    - 1月
    - 2月
    - 3月
    - 4月
    - 5月
    - 6月
    - 7月
    - 8月
    - 9月
    - 10月
    - 11月
    - 12月
    day_names:
    - 星期日
    - 星期一
    - 星期二
    - 星期三
    - 星期四
    - 星期五
    - 星期六
    formats:
      default: ! '%Y-%m-%d'
      long: ! '%Y年%b%d日'
      short: ! '%b%d日'
    month_names:
    -
    - 一月
    - 二月
    - 三月
    - 四月
    - 五月
    - 六月
    - 七月
    - 八月
    - 九月
    - 十月
    - 十一月
    - 十二月
    order:
    - :year
    - :month
    - :day
